language: c++
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update -qq
  - sudo apt-get install octave
script:
  - cd tests && /usr/bin/octave -q --eval test_nekmatlab